# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0JGY9TJwDdxQCv0O_sbbdfjtjLfR65c
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset")

print("Path to dataset files:", path)

# Importamos las bibliotecas que necesitamos
import kagglehub  # Esta biblioteca nos ayuda a descargar datasets de Kaggle
import pandas as pd  # Pandas es genial para trabajar con datos en tablas (DataFrames)

# Descargamos el dataset de Kaggle usando kagglehub
# El nombre del dataset es "pavansubhasht/ibm-hr-analytics-attrition-dataset"
path = kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset")
print("La ruta donde se guardó el dataset es:", path)  # Imprimimos la ruta para verla

# Ahora, necesitamos la ruta completa al archivo CSV dentro del dataset
# El archivo se llama "WA_Fn-UseC_-HR-Employee-Attrition.csv"
ruta_dataset = path + '/WA_Fn-UseC_-HR-Employee-Attrition.csv'

# ¡Cargamos el dataset en un DataFrame de Pandas!
# Usamos la función "read_csv" de Pandas para leer el archivo CSV
df = pd.read_csv(ruta_dataset)

# ¡Empezamos a explorar el dataset!

# Primero, veamos las primeras filas del DataFrame con "head()"
print("\nUn vistazo a las primeras filas del dataset:")
print(df.head())

# Ahora, veamos información general sobre las columnas con "info()"
print("\nInformación sobre las columnas del dataset:")
print(df.info())

# También podemos obtener estadísticas descriptivas con "describe()"
print("\nEstadísticas descriptivas del dataset:")
print(df.describe())

# ¡Ahora vamos a explorar algunas variables importantes!

# Satisfacción laboral:
print("\nSatisfacción laboral:")
print(df['JobSatisfaction'].value_counts())  # Distribución de la satisfacción laboral
print(df['JobSatisfaction'].mean())  # Promedio de satisfacción laboral

# Nivel de ingreso:
print("\nNivel de ingreso:")
print(df['MonthlyIncome'].describe())  # Estadísticas del nivel de ingreso
print(df.sort_values(by=['MonthlyIncome'], ascending=False).head())  # Empleados con mayores ingresos

# Antigüedad:
print("\nAntigüedad:")
print(df['TotalWorkingYears'].describe())  # Estadísticas de la antigüedad
print(df['TotalWorkingYears'].mean())  # Promedio de antigüedad

# Cargo:
print("\nCargo:")
print(df['JobRole'].value_counts())  # Distribución de los cargos

# Educación:
print("\nEducación:")
print(df['Education'].value_counts())  # Distribución del nivel de educación

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el dataset (si no lo has hecho ya)
# ... (código para cargar el dataset con kagglehub o la ruta local)

# 1. Entender la variable "Attrition"
print("Valores únicos de Attrition:", df['Attrition'].unique())
print("\nCantidad de empleados que se quedaron y se fueron:\n", df['Attrition'].value_counts())

# 2. Explorar la relación entre "Attrition" y otras variables
# Variables numéricas
print("\nEstadísticas descriptivas por Attrition:\n", df.groupby('Attrition')['MonthlyIncome', 'Age', 'TotalWorkingYears'].describe())
sns.boxplot(x='Attrition', y='MonthlyIncome', data=df)
plt.title("Relación entre Attrition e Ingreso Mensual")
plt.show()

# Variables categóricas
print("\nTabla de contingencia entre Attrition y JobSatisfaction:\n", pd.crosstab(df['Attrition'], df['JobSatisfaction']))
sns.countplot(x='JobSatisfaction', hue='Attrition', data=df)
plt.title("Relación entre Attrition y Satisfacción Laboral")
plt.show()

# ... (Puedes agregar más análisis para otras variables categóricas)

# 3. Describir el perfil de los empleados
# (Basándote en los resultados de los análisis anteriores)
print("\nPerfil de los empleados que se van:")
# ... (Describe el perfil usando los resultados obtenidos)

print("\nPerfil de los empleados que se quedan:")
# ... (Describe el perfil usando los resultados obtenidos)

# ... (Puedes agregar más visualizaciones y análisis según sea necesario)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub

# Download latest version
path = kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset")

print("Path to dataset files:", path)

# Construir la ruta completa al archivo CSV
ruta_dataset = path + '/WA_Fn-UseC_-HR-Employee-Attrition.csv'

# Cargar el dataset en un DataFrame de Pandas
df = pd.read_csv(ruta_dataset)

# 1. Entender la variable "Attrition"
print("Valores únicos de Attrition:", df['Attrition'].unique())
print("\nCantidad de empleados que se quedaron y se fueron:\n", df['Attrition'].value_counts())

# 2. Explorar la relación entre "Attrition" y otras variables
# Variables numéricas
print("\nEstadísticas descriptivas por Attrition:\n", df.groupby('Attrition')[['MonthlyIncome', 'Age', 'TotalWorkingYears']].describe())
sns.boxplot(x='Attrition', y='MonthlyIncome', data=df)
plt.title("Relación entre Attrition e Ingreso Mensual")
plt.show()

# Variables categóricas
print("\nTabla de contingencia entre Attrition y JobSatisfaction:\n", pd.crosstab(df['Attrition'], df['JobSatisfaction']))
sns.countplot(x='JobSatisfaction', hue='Attrition', data=df)
plt.title("Relación entre Attrition y Satisfacción Laboral")
plt.show()

# 3. Describir el perfil de los empleados
# (Basándote en los resultados de los análisis anteriores)
print("\nPerfil de los empleados que se van:")
# ... (Describe el perfil usando los resultados obtenidos)

print("\nPerfil de los empleados que se quedan:")
# ... (Describe el perfil usando los resultados obtenidos)